In [1]:
from pymongo import MongoClient
import pandas as pd
from datetime import datetime

In [5]:
client = MongoClient("mongodb://root:rootpass@localhost:27017")
print(client.server_info()['version'])

8.2.6

In [6]:
db = client['clinica']
colecao = db['atendimentos']

In [7]:
dados = [
{"tutor":"Ana","animal":"Cachorro","nome_pet":"Rex1","servico":"Consulta","valor":120,"cidade":"Assis","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Bruno","animal":"Gato","nome_pet":"Mimi2","servico":"Vacinação","valor":95,"cidade":"Assis","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Carlos","animal":"Cachorro","nome_pet":"Thor3","servico":"Banho","valor":60,"cidade":"Assis","data":datetime(2026,3,3),"forma_pagamento":"Dinheiro"},
{"tutor":"Daniela","animal":"Ave","nome_pet":"Piu4","servico":"Exame","valor":180,"cidade":"Assis","data":datetime(2026,3,4),"forma_pagamento":"Cartão"},
{"tutor":"Eduardo","animal":"Gato","nome_pet":"Luna5","servico":"Consulta","valor":130,"cidade":"Assis","data":datetime(2026,3,5),"forma_pagamento":"Pix"},
{"tutor":"Fernanda","animal":"Cachorro","nome_pet":"Bob6","servico":"Vacinação","valor":90,"cidade":"Assis","data":datetime(2026,3,6),"forma_pagamento":"Dinheiro"},
{"tutor":"Gabriel","animal":"Coelho","nome_pet":"Pompom7","servico":"Consulta","valor":110,"cidade":"Assis","data":datetime(2026,3,7),"forma_pagamento":"Pix"},
{"tutor":"Helena","animal":"Cachorro","nome_pet":"Mel8","servico":"Cirurgia","valor":820,"cidade":"Assis","data":datetime(2026,3,8),"forma_pagamento":"Cartão"},
{"tutor":"Igor","animal":"Gato","nome_pet":"Simba9","servico":"Banho","valor":55,"cidade":"Assis","data":datetime(2026,3,9),"forma_pagamento":"Cartão"},
{"tutor":"Juliana","animal":"Cachorro","nome_pet":"Nina10","servico":"Consulta","valor":125,"cidade":"Assis","data":datetime(2026,3,10),"forma_pagamento":"Pix"},
{"tutor":"Lucas","animal":"Ave","nome_pet":"Sky11","servico":"Exame","valor":200,"cidade":"Assis","data":datetime(2026,3,11),"forma_pagamento":"Cartão"},
{"tutor":"Mariana","animal":"Gato","nome_pet":"Lili12","servico":"Consulta","valor":135,"cidade":"Assis","data":datetime(2026,3,12),"forma_pagamento":"Pix"},
{"tutor":"Nicolas","animal":"Cachorro","nome_pet":"Bolt13","servico":"Vacinação","valor":100,"cidade":"Assis","data":datetime(2026,3,13),"forma_pagamento":"Dinheiro"},
{"tutor":"Patricia","animal":"Cachorro","nome_pet":"Max14","servico":"Consulta","valor":140,"cidade":"Ourinhos","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Rafael","animal":"Gato","nome_pet":"Mia15","servico":"Banho","valor":65,"cidade":"Ourinhos","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Sofia","animal":"Cachorro","nome_pet":"Luna16","servico":"Cirurgia","valor":900,"cidade":"Ourinhos","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Thiago","animal":"Ave","nome_pet":"Blue17","servico":"Exame","valor":170,"cidade":"Ourinhos","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Vanessa","animal":"Gato","nome_pet":"Nino18","servico":"Consulta","valor":125,"cidade":"Ourinhos","data":datetime(2026,3,5),"forma_pagamento":"Dinheiro"},
{"tutor":"William","animal":"Cachorro","nome_pet":"Thor19","servico":"Vacinação","valor":95,"cidade":"Ourinhos","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Beatriz","animal":"Coelho","nome_pet":"Fluffy20","servico":"Consulta","valor":115,"cidade":"Ourinhos","data":datetime(2026,3,7),"forma_pagamento":"Cartão"},
{"tutor":"Caio","animal":"Cachorro","nome_pet":"Spike21","servico":"Banho","valor":70,"cidade":"Ourinhos","data":datetime(2026,3,8),"forma_pagamento":"Dinheiro"},
{"tutor":"Diego","animal":"Gato","nome_pet":"Tom22","servico":"Consulta","valor":135,"cidade":"Ourinhos","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Elisa","animal":"Cachorro","nome_pet":"Mel23","servico":"Exame","valor":210,"cidade":"Ourinhos","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Felipe","animal":"Ave","nome_pet":"Kiwi24","servico":"Consulta","valor":120,"cidade":"Ourinhos","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Gisele","animal":"Gato","nome_pet":"Nina25","servico":"Vacinação","valor":85,"cidade":"Ourinhos","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
{"tutor":"Hugo","animal":"Cachorro","nome_pet":"Rex26","servico":"Consulta","valor":150,"cidade":"Ourinhos","data":datetime(2026,3,13),"forma_pagamento":"Cartão"},
{"tutor":"Iris","animal":"Cachorro","nome_pet":"Bob27","servico":"Consulta","valor":110,"cidade":"Pompeia","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Joao","animal":"Gato","nome_pet":"Luna28","servico":"Banho","valor":60,"cidade":"Pompeia","data":datetime(2026,3,2),"forma_pagamento":"Dinheiro"},
{"tutor":"Karen","animal":"Cachorro","nome_pet":"Thor29","servico":"Cirurgia","valor":780,"cidade":"Pompeia","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Leo","animal":"Ave","nome_pet":"Sky30","servico":"Exame","valor":160,"cidade":"Pompeia","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Marta","animal":"Gato","nome_pet":"Mimi31","servico":"Consulta","valor":120,"cidade":"Pompeia","data":datetime(2026,3,5),"forma_pagamento":"Cartão"},
{"tutor":"Nelson","animal":"Cachorro","nome_pet":"Max32","servico":"Vacinação","valor":90,"cidade":"Pompeia","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Olga","animal":"Coelho","nome_pet":"Pompom33","servico":"Consulta","valor":105,"cidade":"Pompeia","data":datetime(2026,3,7),"forma_pagamento":"Dinheiro"},
{"tutor":"Paulo","animal":"Cachorro","nome_pet":"Bolt34","servico":"Banho","valor":75,"cidade":"Pompeia","data":datetime(2026,3,8),"forma_pagamento":"Cartão"},
{"tutor":"Quezia","animal":"Gato","nome_pet":"Simba35","servico":"Consulta","valor":130,"cidade":"Pompeia","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Renato","animal":"Cachorro","nome_pet":"Nina36","servico":"Exame","valor":190,"cidade":"Pompeia","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Sara","animal":"Ave","nome_pet":"Blue37","servico":"Consulta","valor":115,"cidade":"Pompeia","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Tiago","animal":"Gato","nome_pet":"Lili38","servico":"Vacinação","valor":85,"cidade":"Pompeia","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
{"tutor":"Ursula","animal":"Cachorro","nome_pet":"Rex39","servico":"Consulta","valor":145,"cidade":"Marilia","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Vitor","animal":"Gato","nome_pet":"Mia40","servico":"Banho","valor":70,"cidade":"Marilia","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Wesley","animal":"Cachorro","nome_pet":"Thor41","servico":"Cirurgia","valor":870,"cidade":"Marilia","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Xuxa","animal":"Ave","nome_pet":"Piu42","servico":"Exame","valor":175,"cidade":"Marilia","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Yara","animal":"Gato","nome_pet":"Luna43","servico":"Consulta","valor":135,"cidade":"Marilia","data":datetime(2026,3,5),"forma_pagamento":"Dinheiro"},
{"tutor":"Zeca","animal":"Cachorro","nome_pet":"Bob44","servico":"Vacinação","valor":100,"cidade":"Marilia","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Aline","animal":"Coelho","nome_pet":"Fluffy45","servico":"Consulta","valor":120,"cidade":"Marilia","data":datetime(2026,3,7),"forma_pagamento":"Cartão"},
{"tutor":"Bruna","animal":"Cachorro","nome_pet":"Spike46","servico":"Banho","valor":80,"cidade":"Marilia","data":datetime(2026,3,8),"forma_pagamento":"Dinheiro"},
{"tutor":"Cesar","animal":"Gato","nome_pet":"Tom47","servico":"Consulta","valor":140,"cidade":"Marilia","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Dora","animal":"Cachorro","nome_pet":"Mel48","servico":"Exame","valor":220,"cidade":"Marilia","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Enzo","animal":"Ave","nome_pet":"Kiwi49","servico":"Consulta","valor":130,"cidade":"Marilia","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Fabio","animal":"Gato","nome_pet":"Nina50","servico":"Vacinação","valor":90,"cidade":"Marilia","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
]

In [8]:
colecao.insert_many(dados)

InsertManyResult([ObjectId('69c5d53f001ba0b66f65744b'), ObjectId('69c5d53f001ba0b66f65744c'), ObjectId('69c5d53f001ba0b66f65744d'), ObjectId('69c5d53f001ba0b66f65744e'), ObjectId('69c5d53f001ba0b66f65744f'), ObjectId('69c5d53f001ba0b66f657450'), ObjectId('69c5d53f001ba0b66f657451'), ObjectId('69c5d53f001ba0b66f657452'), ObjectId('69c5d53f001ba0b66f657453'), ObjectId('69c5d53f001ba0b66f657454'), ObjectId('69c5d53f001ba0b66f657455'), ObjectId('69c5d53f001ba0b66f657456'), ObjectId('69c5d53f001ba0b66f657457'), ObjectId('69c5d53f001ba0b66f657458'), ObjectId('69c5d53f001ba0b66f657459'), ObjectId('69c5d53f001ba0b66f65745a'), ObjectId('69c5d53f001ba0b66f65745b'), ObjectId('69c5d53f001ba0b66f65745c'), ObjectId('69c5d53f001ba0b66f65745d'), ObjectId('69c5d53f001ba0b66f65745e'), ObjectId('69c5d53f001ba0b66f65745f'), ObjectId('69c5d53f001ba0b66f657460'), ObjectId('69c5d53f001ba0b66f657461'), ObjectId('69c5d53f001ba0b66f657462'), ObjectId('69c5d53f001ba0b66f657463'), ObjectId('69c5d53f001ba0b66f657464'), ObjectId('69c5d53f001ba0b66f657465'), ObjectId('69c5d53f001ba0b66f657466'), ObjectId('69c5d53f001ba0b66f657467'), ObjectId('69c5d53f001ba0b66f657468'), ObjectId('69c5d53f001ba0b66f657469'), ObjectId('69c5d53f001ba0b66f65746a'), ObjectId('69c5d53f001ba0b66f65746b'), ObjectId('69c5d53f001ba0b66f65746c'), ObjectId('69c5d53f001ba0b66f65746d'), ObjectId('69c5d53f001ba0b66f65746e'), ObjectId('69c5d53f001ba0b66f65746f'), ObjectId('69c5d53f001ba0b66f657470'), ObjectId('69c5d53f001ba0b66f657471'), ObjectId('69c5d53f001ba0b66f657472'), ObjectId('69c5d53f001ba0b66f657473'), ObjectId('69c5d53f001ba0b66f657474'), ObjectId('69c5d53f001ba0b66f657475'), ObjectId('69c5d53f001ba0b66f657476'), ObjectId('69c5d53f001ba0b66f657477'), ObjectId('69c5d53f001ba0b66f657478'), ObjectId('69c5d53f001ba0b66f657479'), ObjectId('69c5d53f001ba0b66f65747a'), ObjectId('69c5d53f001ba0b66f65747b'), ObjectId('69c5d53f001ba0b66f65747c')], acknowledged=True)

In [10]:
dados_preco = list(colecao.find({
    'valor': {'$gte' : 90, '$lte': 200}
}))
display(dados_preco)

[{'_id': ObjectId('69c5d53f001ba0b66f65744b'),
  'tutor': 'Ana',
  'animal': 'Cachorro',
  'nome_pet': 'Rex1',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f65744c'),
  'tutor': 'Bruno',
  'animal': 'Gato',
  'nome_pet': 'Mimi2',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f65744e'),
  'tutor': 'Daniela',
  'animal': 'Ave',
  'nome_pet': 'Piu4',
  'servico': 'Exame',
  'valor': 180,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f65744f'),
  'tutor': 'Eduardo',
  'animal': 'Gato',
  'nome_pet': 'Luna5',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657450'),
  'tutor': 'Fernanda',
  'animal': 'Cachorro',
  'nome_pet': 'Bob6',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f657451'),
  'tutor': 'Gabriel',
  'animal': 'Coelho',
  'nome_pet': 'Pompom7',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657454'),
  'tutor': 'Juliana',
  'animal': 'Cachorro',
  'nome_pet': 'Nina10',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657455'),
  'tutor': 'Lucas',
  'animal': 'Ave',
  'nome_pet': 'Sky11',
  'servico': 'Exame',
  'valor': 200,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f657456'),
  'tutor': 'Mariana',
  'animal': 'Gato',
  'nome_pet': 'Lili12',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657457'),
  'tutor': 'Nicolas',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt13',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f657458'),
  'tutor': 'Patricia',
  'animal': 'Cachorro',
  'nome_pet': 'Max14',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f65745b'),
  'tutor': 'Thiago',
  'animal': 'Ave',
  'nome_pet': 'Blue17',
  'servico': 'Exame',
  'valor': 170,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f65745c'),
  'tutor': 'Vanessa',
  'animal': 'Gato',
  'nome_pet': 'Nino18',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f65745d'),
  'tutor': 'William',
  'animal': 'Cachorro',
  'nome_pet': 'Thor19',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f65745e'),
  'tutor': 'Beatriz',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy20',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f657460'),
  'tutor': 'Diego',
  'animal': 'Gato',
  'nome_pet': 'Tom22',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657462'),
  'tutor': 'Felipe',
  'animal': 'Ave',
  'nome_pet': 'Kiwi24',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657464'),
  'tutor': 'Hugo',
  'animal': 'Cachorro',
  'nome_pet': 'Rex26',
  'servico': 'Consulta',
  'valor': 150,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f657465'),
  'tutor': 'Iris',
  'animal': 'Cachorro',
  'nome_pet': 'Bob27',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657468'),
  'tutor': 'Leo',
  'animal': 'Ave',
  'nome_pet': 'Sky30',
  'servico': 'Exame',
  'valor': 160,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657469'),
  'tutor': 'Marta',
  'animal': 'Gato',
  'nome_pet': 'Mimi31',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f65746a'),
  'tutor': 'Nelson',
  'animal': 'Cachorro',
  'nome_pet': 'Max32',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f65746b'),
  'tutor': 'Olga',
  'animal': 'Coelho',
  'nome_pet': 'Pompom33',
  'servico': 'Consulta',
  'valor': 105,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f65746d'),
  'tutor': 'Quezia',
  'animal': 'Gato',
  'nome_pet': 'Simba35',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f65746e'),
  'tutor': 'Renato',
  'animal': 'Cachorro',
  'nome_pet': 'Nina36',
  'servico': 'Exame',
  'valor': 190,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f65746f'),
  'tutor': 'Sara',
  'animal': 'Ave',
  'nome_pet': 'Blue37',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657471'),
  'tutor': 'Ursula',
  'animal': 'Cachorro',
  'nome_pet': 'Rex39',
  'servico': 'Consulta',
  'valor': 145,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657474'),
  'tutor': 'Xuxa',
  'animal': 'Ave',
  'nome_pet': 'Piu42',
  'servico': 'Exame',
  'valor': 175,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657475'),
  'tutor': 'Yara',
  'animal': 'Gato',
  'nome_pet': 'Luna43',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f657476'),
  'tutor': 'Zeca',
  'animal': 'Cachorro',
  'nome_pet': 'Bob44',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657477'),
  'tutor': 'Aline',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy45',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f657479'),
  'tutor': 'Cesar',
  'animal': 'Gato',
  'nome_pet': 'Tom47',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f65747b'),
  'tutor': 'Enzo',
  'animal': 'Ave',
  'nome_pet': 'Kiwi49',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f65747c'),
  'tutor': 'Fabio',
  'animal': 'Gato',
  'nome_pet': 'Nina50',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'}]

In [11]:
dados_cidade = list(colecao.find({
    'cidade': {'$in' : ['Assis', 'Ourinhos', 'Pompeia', 'Marilia']}
}))
display(dados_cidade)

[{'_id': ObjectId('69c5d53f001ba0b66f65744b'),
  'tutor': 'Ana',
  'animal': 'Cachorro',
  'nome_pet': 'Rex1',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f65744c'),
  'tutor': 'Bruno',
  'animal': 'Gato',
  'nome_pet': 'Mimi2',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f65744d'),
  'tutor': 'Carlos',
  'animal': 'Cachorro',
  'nome_pet': 'Thor3',
  'servico': 'Banho',
  'valor': 60,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f65744e'),
  'tutor': 'Daniela',
  'animal': 'Ave',
  'nome_pet': 'Piu4',
  'servico': 'Exame',
  'valor': 180,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f65744f'),
  'tutor': 'Eduardo',
  'animal': 'Gato',
  'nome_pet': 'Luna5',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657450'),
  'tutor': 'Fernanda',
  'animal': 'Cachorro',
  'nome_pet': 'Bob6',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f657451'),
  'tutor': 'Gabriel',
  'animal': 'Coelho',
  'nome_pet': 'Pompom7',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657452'),
  'tutor': 'Helena',
  'animal': 'Cachorro',
  'nome_pet': 'Mel8',
  'servico': 'Cirurgia',
  'valor': 820,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f657453'),
  'tutor': 'Igor',
  'animal': 'Gato',
  'nome_pet': 'Simba9',
  'servico': 'Banho',
  'valor': 55,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f657454'),
  'tutor': 'Juliana',
  'animal': 'Cachorro',
  'nome_pet': 'Nina10',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657455'),
  'tutor': 'Lucas',
  'animal': 'Ave',
  'nome_pet': 'Sky11',
  'servico': 'Exame',
  'valor': 200,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f657456'),
  'tutor': 'Mariana',
  'animal': 'Gato',
  'nome_pet': 'Lili12',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657457'),
  'tutor': 'Nicolas',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt13',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f657458'),
  'tutor': 'Patricia',
  'animal': 'Cachorro',
  'nome_pet': 'Max14',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657459'),
  'tutor': 'Rafael',
  'animal': 'Gato',
  'nome_pet': 'Mia15',
  'servico': 'Banho',
  'valor': 65,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f65745a'),
  'tutor': 'Sofia',
  'animal': 'Cachorro',
  'nome_pet': 'Luna16',
  'servico': 'Cirurgia',
  'valor': 900,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f65745b'),
  'tutor': 'Thiago',
  'animal': 'Ave',
  'nome_pet': 'Blue17',
  'servico': 'Exame',
  'valor': 170,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f65745c'),
  'tutor': 'Vanessa',
  'animal': 'Gato',
  'nome_pet': 'Nino18',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f65745d'),
  'tutor': 'William',
  'animal': 'Cachorro',
  'nome_pet': 'Thor19',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f65745e'),
  'tutor': 'Beatriz',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy20',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f65745f'),
  'tutor': 'Caio',
  'animal': 'Cachorro',
  'nome_pet': 'Spike21',
  'servico': 'Banho',
  'valor': 70,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f657460'),
  'tutor': 'Diego',
  'animal': 'Gato',
  'nome_pet': 'Tom22',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657461'),
  'tutor': 'Elisa',
  'animal': 'Cachorro',
  'nome_pet': 'Mel23',
  'servico': 'Exame',
  'valor': 210,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f657462'),
  'tutor': 'Felipe',
  'animal': 'Ave',
  'nome_pet': 'Kiwi24',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657463'),
  'tutor': 'Gisele',
  'animal': 'Gato',
  'nome_pet': 'Nina25',
  'servico': 'Vacinação',
  'valor': 85,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f657464'),
  'tutor': 'Hugo',
  'animal': 'Cachorro',
  'nome_pet': 'Rex26',
  'servico': 'Consulta',
  'valor': 150,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f657465'),
  'tutor': 'Iris',
  'animal': 'Cachorro',
  'nome_pet': 'Bob27',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657466'),
  'tutor': 'Joao',
  'animal': 'Gato',
  'nome_pet': 'Luna28',
  'servico': 'Banho',
  'valor': 60,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f657467'),
  'tutor': 'Karen',
  'animal': 'Cachorro',
  'nome_pet': 'Thor29',
  'servico': 'Cirurgia',
  'valor': 780,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f657468'),
  'tutor': 'Leo',
  'animal': 'Ave',
  'nome_pet': 'Sky30',
  'servico': 'Exame',
  'valor': 160,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657469'),
  'tutor': 'Marta',
  'animal': 'Gato',
  'nome_pet': 'Mimi31',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f65746a'),
  'tutor': 'Nelson',
  'animal': 'Cachorro',
  'nome_pet': 'Max32',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f65746b'),
  'tutor': 'Olga',
  'animal': 'Coelho',
  'nome_pet': 'Pompom33',
  'servico': 'Consulta',
  'valor': 105,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f65746c'),
  'tutor': 'Paulo',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt34',
  'servico': 'Banho',
  'valor': 75,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f65746d'),
  'tutor': 'Quezia',
  'animal': 'Gato',
  'nome_pet': 'Simba35',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f65746e'),
  'tutor': 'Renato',
  'animal': 'Cachorro',
  'nome_pet': 'Nina36',
  'servico': 'Exame',
  'valor': 190,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f65746f'),
  'tutor': 'Sara',
  'animal': 'Ave',
  'nome_pet': 'Blue37',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657470'),
  'tutor': 'Tiago',
  'animal': 'Gato',
  'nome_pet': 'Lili38',
  'servico': 'Vacinação',
  'valor': 85,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f657471'),
  'tutor': 'Ursula',
  'animal': 'Cachorro',
  'nome_pet': 'Rex39',
  'servico': 'Consulta',
  'valor': 145,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657472'),
  'tutor': 'Vitor',
  'animal': 'Gato',
  'nome_pet': 'Mia40',
  'servico': 'Banho',
  'valor': 70,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f657473'),
  'tutor': 'Wesley',
  'animal': 'Cachorro',
  'nome_pet': 'Thor41',
  'servico': 'Cirurgia',
  'valor': 870,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f657474'),
  'tutor': 'Xuxa',
  'animal': 'Ave',
  'nome_pet': 'Piu42',
  'servico': 'Exame',
  'valor': 175,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657475'),
  'tutor': 'Yara',
  'animal': 'Gato',
  'nome_pet': 'Luna43',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f657476'),
  'tutor': 'Zeca',
  'animal': 'Cachorro',
  'nome_pet': 'Bob44',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f657477'),
  'tutor': 'Aline',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy45',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f657478'),
  'tutor': 'Bruna',
  'animal': 'Cachorro',
  'nome_pet': 'Spike46',
  'servico': 'Banho',
  'valor': 80,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c5d53f001ba0b66f657479'),
  'tutor': 'Cesar',
  'animal': 'Gato',
  'nome_pet': 'Tom47',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f65747a'),
  'tutor': 'Dora',
  'animal': 'Cachorro',
  'nome_pet': 'Mel48',
  'servico': 'Exame',
  'valor': 220,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c5d53f001ba0b66f65747b'),
  'tutor': 'Enzo',
  'animal': 'Ave',
  'nome_pet': 'Kiwi49',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c5d53f001ba0b66f65747c'),
  'tutor': 'Fabio',
  'animal': 'Gato',
  'nome_pet': 'Nina50',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'}]

In [12]:
df = pd.DataFrame(dados_cidade)
df

,_id,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento
0,69c5d53f001ba0b66f65744b,Ana,Cachorro,Rex1,Consulta,120,Assis,2026-03-01,Pix
1,69c5d53f001ba0b66f65744c,Bruno,Gato,Mimi2,Vacinação,95,Assis,2026-03-02,Cartão
2,69c5d53f001ba0b66f65744d,Carlos,Cachorro,Thor3,Banho,60,Assis,2026-03-03,Dinheiro
3,69c5d53f001ba0b66f65744e,Daniela,Ave,Piu4,Exame,180,Assis,2026-03-04,Cartão
4,69c5d53f001ba0b66f65744f,Eduardo,Gato,Luna5,Consulta,130,Assis,2026-03-05,Pix
5,69c5d53f001ba0b66f657450,Fernanda,Cachorro,Bob6,Vacinação,90,Assis,2026-03-06,Dinheiro
6,69c5d53f001ba0b66f657451,Gabriel,Coelho,Pompom7,Consulta,110,Assis,2026-03-07,Pix
7,69c5d53f001ba0b66f657452,Helena,Cachorro,Mel8,Cirurgia,820,Assis,2026-03-08,Cartão
8,69c5d53f001ba0b66f657453,Igor,Gato,Simba9,Banho,55,Assis,2026-03-09,Cartão
9,69c5d53f001ba0b66f657454,Juliana,Cachorro,Nina10,Consulta,125,Assis,2026-03-10,Pix
10,69c5d53f001ba0b66f657455,Lucas,Ave,Sky11,Exame,200,Assis,2026-03-11,Cartão
11,69c5d53f001ba0b66f657456,Mariana,Gato,Lili12,Consulta,135,Assis,2026-03-12,Pix
12,69c5d53f001ba0b66f657457,Nicolas,Cachorro,Bolt13,Vacinação,100,Assis,2026-03-13,Dinheiro
13,69c5d53f001ba0b66f657458,Patricia,Cachorro,Max14,Consulta,140,Ourinhos,2026-03-01,Pix
14,69c5d53f001ba0b66f657459,Rafael,Gato,Mia15,Banho,65,Ourinhos,2026-03-02,Cartão
15,69c5d53f001ba0b66f65745a,Sofia,Cachorro,Luna16,Cirurgia,900,Ourinhos,2026-03-03,Cartão
16,69c5d53f001ba0b66f65745b,Thiago,Ave,Blue17,Exame,170,Ourinhos,2026-03-04,Pix
17,69c5d53f001ba0b66f65745c,Vanessa,Gato,Nino18,Consulta,125,Ourinhos,2026-03-05,Dinheiro
18,69c5d53f001ba0b66f65745d,William,Cachorro,Thor19,Vacinação,95,Ourinhos,2026-03-06,Pix
19,69c5d53f001ba0b66f65745e,Beatriz,Coelho,Fluffy20,Consulta,115,Ourinhos,2026-03-07,Cartão
20,69c5d53f001ba0b66f65745f,Caio,Cachorro,Spike21,Banho,70,Ourinhos,2026-03-08,Dinheiro
21,69c5d53f001ba0b66f657460,Diego,Gato,Tom22,Consulta,135,Ourinhos,2026-03-09,Pix
22,69c5d53f001ba0b66f657461,Elisa,Cachorro,Mel23,Exame,210,Ourinhos,2026-03-10,Cartão
23,69c5d53f001ba0b66f657462,Felipe,Ave,Kiwi24,Consulta,120,Ourinhos,2026-03-11,Pix
24,69c5d53f001ba0b66f657463,Gisele,Gato,Nina25,Vacinação,85,Ourinhos,2026-03-12,Dinheiro
25,69c5d53f001ba0b66f657464,Hugo,Cachorro,Rex26,Consulta,150,Ourinhos,2026-03-13,Cartão
26,69c5d53f001ba0b66f657465,Iris,Cachorro,Bob27,Consulta,110,Pompeia,2026-03-01,Pix
27,69c5d53f001ba0b66f657466,Joao,Gato,Luna28,Banho,60,Pompeia,2026-03-02,Dinheiro
28,69c5d53f001ba0b66f657467,Karen,Cachorro,Thor29,Cirurgia,780,Pompeia,2026-03-03,Cartão
29,69c5d53f001ba0b66f657468,Leo,Ave,Sky30,Exame,160,Pompeia,2026-03-04,Pix
30,69c5d53f001ba0b66f657469,Marta,Gato,Mimi31,Consulta,120,Pompeia,2026-03-05,Cartão
31,69c5d53f001ba0b66f65746a,Nelson,Cachorro,Max32,Vacinação,90,Pompeia,2026-03-06,Pix
32,69c5d53f001ba0b66f65746b,Olga,Coelho,Pompom33,Consulta,105,Pompeia,2026-03-07,Dinheiro
33,69c5d53f001ba0b66f65746c,Paulo,Cachorro,Bolt34,Banho,75,Pompeia,2026-03-08,Cartão
34,69c5d53f001ba0b66f65746d,Quezia,Gato,Simba35,Consulta,130,Pompeia,2026-03-09,Pix
35,69c5d53f001ba0b66f65746e,Renato,Cachorro,Nina36,Exame,190,Pompeia,2026-03-10,Cartão
36,69c5d53f001ba0b66f65746f,Sara,Ave,Blue37,Consulta,115,Pompeia,2026-03-11,Pix
37,69c5d53f001ba0b66f657470,Tiago,Gato,Lili38,Vacinação,85,Pompeia,2026-03-12,Dinheiro
38,69c5d53f001ba0b66f657471,Ursula,Cachorro,Rex39,Consulta,145,Marilia,2026-03-01,Pix
39,69c5d53f001ba0b66f657472,Vitor,Gato,Mia40,Banho,70,Marilia,2026-03-02,Cartão
40,69c5d53f001ba0b66f657473,Wesley,Cachorro,Thor41,Cirurgia,870,Marilia,2026-03-03,Cartão
41,69c5d53f001ba0b66f657474,Xuxa,Ave,Piu42,Exame,175,Marilia,2026-03-04,Pix
42,69c5d53f001ba0b66f657475,Yara,Gato,Luna43,Consulta,135,Marilia,2026-03-05,Dinheiro
43,69c5d53f001ba0b66f657476,Zeca,Cachorro,Bob44,Vacinação,100,Marilia,2026-03-06,Pix
44,69c5d53f001ba0b66f657477,Aline,Coelho,Fluffy45,Consulta,120,Marilia,2026-03-07,Cartão
45,69c5d53f001ba0b66f657478,Bruna,Cachorro,Spike46,Banho,80,Marilia,2026-03-08,Dinheiro
46,69c5d53f001ba0b66f657479,Cesar,Gato,Tom47,Consulta,140,Marilia,2026-03-09,Pix
47,69c5d53f001ba0b66f65747a,Dora,Cachorro,Mel48,Exame,220,Marilia,2026-03-10,Cartão
48,69c5d53f001ba0b66f65747b,Enzo,Ave,Kiwi49,Consulta,130,Marilia,2026-03-11,Pix
49,69c5d53f001ba0b66f65747c,Fabio,Gato,Nina50,Vacinação,90,Marilia,2026-03-12,Dinheiro

In [13]:
df.isnull().sum()

_id                0
tutor              0
animal             0
nome_pet           0
servico            0
valor              0
cidade             0
data               0
forma_pagamento    0
dtype: int64

In [14]:
faturamento = df['valor'].sum()
print(f"Faturamento Total: {faturamento:.2f}")

Faturamento Total: 8895.00

In [18]:
faturamento_cidade = df.groupby('cidade')['valor'].sum()
print("Faturamento por cidade: ", faturamento_cidade)

Faturamento por cidade:  cidade
Assis       2220
Marilia     2275
Ourinhos    2380
Pompeia     2020
Name: valor, dtype: int64

In [19]:
faturamento_servico = df.groupby('servico')['valor'].sum()
print('Faturamento por serviço: ', faturamento_servico)

Faturamento por serviço:  servico
Banho         535
Cirurgia     3370
Consulta     2655
Exame        1505
Vacinação     830
Name: valor, dtype: int64

In [21]:
ticket_medio = df['valor'].mean()
print(f"Ticket Médio: {ticket_medio:.2f}")

Ticket Médio: 177.90

In [25]:
ticket_medio_cidade = df.groupby('cidade')['valor'].mean()
for cidade, valor in ticket_medio_cidade.items():
    print(cidade, ' : ', f"{valor:.2f}")

Assis  :  170.77
Marilia  :  189.58
Ourinhos  :  183.08
Pompeia  :  168.33

In [26]:
servico_top = df.groupby('servico')['valor'].sum().idxmax()
servico_top

'Cirurgia'

In [27]:
cidade_top = df.groupby('cidade')['valor'].sum().idxmax()
cidade_top

'Ourinhos'

In [34]:
top_3_atentimentos = df.sort_values(by='valor', ascending=False).head(3)
top_3_atentimentos

,_id,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento
15,69c5d53f001ba0b66f65745a,Sofia,Cachorro,Luna16,Cirurgia,900,Ourinhos,2026-03-03,Cartão
40,69c5d53f001ba0b66f657473,Wesley,Cachorro,Thor41,Cirurgia,870,Marilia,2026-03-03,Cartão
7,69c5d53f001ba0b66f657452,Helena,Cachorro,Mel8,Cirurgia,820,Assis,2026-03-08,Cartão

In [40]:
relatorio = {
    'data_geracao' : datetime.now(),
    'faturamento_total' : float(faturamento),
    'faturamento_por_cidade' : faturamento_cidade.to_dict(),
    'faturamento_por_servico' : faturamento_servico.to_dict(),
    'ticket_medio_geral' : float(ticket_medio),
    'ticket_medio_por_cidade' : ticket_medio_cidade.to_dict(),
    'servico_top' : servico_top,
    'cidade_top' : cidade_top,
    'top_3_atentimentos' : list(top_3_atentimentos)
}
display(relatorio)

{'data_geracao': datetime.datetime(2026, 3, 27, 1, 29, 51, 43257),
 'faturamento_total': 8895.0,
 'faturamento_por_cidade': {'Assis': 2220,
  'Marilia': 2275,
  'Ourinhos': 2380,
  'Pompeia': 2020},
 'faturamento_por_servico': {'Banho': 535,
  'Cirurgia': 3370,
  'Consulta': 2655,
  'Exame': 1505,
  'Vacinação': 830},
 'ticket_medio_geral': 177.9,
 'ticket_medio_por_cidade': {'Assis': 170.76923076923077,
  'Marilia': 189.58333333333334,
  'Ourinhos': 183.07692307692307,
  'Pompeia': 168.33333333333334},
 'servico_top': 'Cirurgia',
 'cidade_top': 'Ourinhos',
 'top_3_atentimentos': ['_id',
  'tutor',
  'animal',
  'nome_pet',
  'servico',
  'valor',
  'cidade',
  'data',
  'forma_pagamento']}

In [41]:
colecao_relatorios = db['relatorios']
colecao_relatorios.insert_one(relatorio)

InsertOneResult(ObjectId('69c5ddb8001ba0b66f65747d'), acknowledged=True)

In [42]:
for r in colecao_relatorios.find():
    display(r)

{'_id': ObjectId('69c5ddb8001ba0b66f65747d'),
 'data_geracao': datetime.datetime(2026, 3, 27, 1, 29, 51, 43000),
 'faturamento_total': 8895.0,
 'faturamento_por_cidade': {'Assis': 2220,
  'Marilia': 2275,
  'Ourinhos': 2380,
  'Pompeia': 2020},
 'faturamento_por_servico': {'Banho': 535,
  'Cirurgia': 3370,
  'Consulta': 2655,
  'Exame': 1505,
  'Vacinação': 830},
 'ticket_medio_geral': 177.9,
 'ticket_medio_por_cidade': {'Assis': 170.76923076923077,
  'Marilia': 189.58333333333334,
  'Ourinhos': 183.07692307692307,
  'Pompeia': 168.33333333333334},
 'servico_top': 'Cirurgia',
 'cidade_top': 'Ourinhos',
 'top_3_atentimentos': ['_id',
  'tutor',
  'animal',
  'nome_pet',
  'servico',
  'valor',
  'cidade',
  'data',
  'forma_pagamento']}